# permissions for end users to edit projectvendings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectvending-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devsabayops-operator
    app.kubernetes.io/part-of: devsabayops-operator
    app.kubernetes.io/managed-by: kustomize
  name: projectvending-editor-role
rules:
- apiGroups:
  - devsabayops.teambeata.com
  resources:
  - projectvendings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devsabayops.teambeata.com
  resources:
  - projectvendings/status
  verbs:
  - get
