---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devsabayops.teambeata.com
  resources:
  - projectvendings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devsabayops.teambeata.com
  resources:
  - projectvendings/finalizers
  verbs:
  - update
- apiGroups:
  - devsabayops.teambeata.com
  resources:
  - projectvendings/status
  verbs:
  - get
  - patch
  - update
